const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),stats=document.getElementById('stats'),message=document.getElementById('message');
let px=0,py=0,time=6,day=1,hp=100,food=100,wood=0,stone=0,berries=0,axe=false,pick=false,raft=false,won=false,dead=false;
let W=innerWidth,H=innerHeight,last=performance.now(),jx=0,jy=0,seed=7;const nodes=[];
function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}function resize(){W=innerWidth;H=innerHeight;canvas.width=Math.floor(W*devicePixelRatio);canvas.height=Math.floor(H*devicePixelRatio);ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}addEventListener('resize',resize);resize();
for(let i=0;i<42;i++){let a=rand()*Math.PI*2,d=160+rand()*650;nodes.push({x:Math.cos(a)*d,y:Math.sin(a)*d,t:i%3,alive:true})}nodes.push({x:720,y:0,t:3,alive:true});
function save(){localStorage.setItem('survivalIslandSave',JSON.stringify({px,py,time,day,hp,food,wood,stone,berries,axe,pick,raft}))}function load(){try{let s=JSON.parse(localStorage.getItem('survivalIslandSave'));if(s)({px,py,time,day,hp,food,wood,stone,berries,axe,pick,raft}=s)}catch(e){}}load();
const joy=document.getElementById('joystick'),stick=document.getElementById('stick');function moveJoy(e){let r=joy.getBoundingClientRect(),x=e.clientX-r.left-67.5,y=e.clientY-r.top-67.5,d=Math.hypot(x,y),m=48;if(d>m){x*=m/d;y*=m/d}stick.style.transform=`translate(${x}px,${y}px)`;jx=x/m;jy=y/m}joy.addEventListener('pointerdown',e=>{joy.setPointerCapture(e.pointerId);moveJoy(e)});joy.addEventListener('pointermove',e=>{if(e.buttons)moveJoy(e)});function stopJoy(){jx=jy=0;stick.style.transform='translate(0,0)'}joy.addEventListener('pointerup',stopJoy);joy.addEventListener('pointercancel',stopJoy);
document.getElementById('use').onclick=use;document.getElementById('craft').onclick=craft;document.getElementById('save').onclick=()=>{save();flash('SAVED')};document.getElementById('eat').onclick=eat;
function flash(t){message.textContent=t;setTimeout(()=>{if(message.textContent===t)message.textContent=''},1200)}function use(){let b=null,d=65;for(const n of nodes){let q=Math.hypot(px-n.x,py-n.y);if(n.alive&&q<d){b=n;d=q}}if(!b){flash('MOVE CLOSER');return}if(b.t===0){if(!axe){axe=true;flash('AXE FOUND')}else{wood+=4;b.alive=false;flash('+4 WOOD')}}else if(b.t===1){if(!pick){pick=true;flash('PICKAXE FOUND')}else{stone+=3;b.alive=false;flash('+3 STONE')}}else if(b.t===2){berries+=2;b.alive=false;flash('+2 BERRIES')}else if(b.t===3&&raft){won=true;save();flash('YOU ESCAPED!')}}
function craft(){if(!axe&&wood>=3){wood-=3;axe=true;flash('AXE CRAFTED')}else if(!pick&&wood>=2&&stone>=2){wood-=2;stone-=2;pick=true;flash('PICKAXE CRAFTED')}else if(!raft&&wood>=30&&stone>=10){wood-=30;stone-=10;raft=true;flash('RAFT BUILT — GO TO THE BEACH')}else flash('NOT ENOUGH MATERIALS')}
function eat(){if(berries>0&&food<100){berries--;food=Math.min(100,food+25);flash('ATE BERRIES')}else flash('NO BERRIES OR NOT HUNGRY')}
function nodeDraw(n,cx,cy){let x=n.x+cx,y=n.y+cy;if(n.t===0){ctx.fillStyle='#70452c';ctx.fillRect(x-7,y-2,14,30);ctx.fillStyle='#28783a';ctx.beginPath();ctx.arc(x,y-20,30,0,Math.PI*2);ctx.fill();ctx.fillStyle='#39944a';ctx.beginPath();ctx.arc(x-12,y-10,17,0,Math.PI*2);ctx.fill()}else if(n.t===1){ctx.fillStyle='#777';ctx.fillRect(x-24,y-15,48,30);ctx.fillStyle='#999';ctx.fillRect(x-10,y-10,17,6)}else if(n.t===2){ctx.fillStyle='#39743b';ctx.fillRect(x-5,y-3,10,27);ctx.fillStyle='#df3155';for(let i=0;i<3;i++){ctx.beginPath();ctx.arc(x+(i-1)*9,y-14-(i===1?5:0),8,0,Math.PI*2);ctx.fill()}}else{ctx.fillStyle='#8b542e';ctx.fillRect(x-38,y-12,76,24);ctx.fillStyle='#c9914c';ctx.fillRect(x-28,y-5,56,5)}}
function frame(now){let dt=Math.min(.05,(now-last)/1000);last=now;if(!won&&!dead){px+=jx*150*dt;py+=jy*150*dt;let q=Math.hypot(px,py);if(q>900){px*=900/q;py*=900/q}time+=dt/20;if(time>=24){time-=24;day++;save()}food-=dt*.65;if(food<=0){food=0;hp-=dt*3}if(hp<=0){hp=0;dead=true;save()}}
ctx.clearRect(0,0,W,H);ctx.fillStyle='#3791be';ctx.fillRect(0,0,W,H);let cx=W/2-px,cy=H/2-py;ctx.fillStyle='#dfbe66';ctx.beginPath();ctx.arc(cx,cy,930,0,Math.PI*2);ctx.fill();ctx.fillStyle='#4aa04c';ctx.beginPath();ctx.arc(cx,cy,850,0,Math.PI*2);ctx.fill();for(const n of nodes)if(n.alive)nodeDraw(n,cx,cy);ctx.fillStyle='#304c78';ctx.fillRect(W/2-12,H/2-20,24,35);ctx.fillStyle='#e8b587';ctx.fillRect(W/2-10,H/2-40,20,20);if(time>=18||time<6){ctx.fillStyle='#88000020';ctx.fillRect(0,0,W,H)}stats.textContent=`DAY ${day}  ${String(Math.floor(time)).padStart(2,'0')}:${String(Math.floor(time%1*60)).padStart(2,'0')} | HP ${Math.floor(hp)} FOOD ${Math.floor(food)} | WOOD ${wood} STONE ${stone} BERRY ${berries}`;if(won||dead){message.className='ending';message.textContent=won?'YOU ESCAPED!':'YOU DIED'}requestAnimationFrame(frame)}requestAnimationFrame(frame);
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
